# Generated by Django 4.1.5 on 2023-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
